name: Deploy backend
on: [push]
jobs:
  Deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.x"
          include-prerelease: true
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: dotnet publish
        run: dotnet publish -c Release -o /Users/ebizimoh/Documents/Integrify_Files/fs15_Fullstack/backend/WebApi.Infrastructure/bin
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: /Users/ebizimoh/Documents/Integrify_Files/fs15_Fullstack/backend/WebApi.Infrastructure/bin
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "LibMgtSyst"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_d2b9e8deb42f434aacee887b01d1edaf }}
          package: .
